import requests

# response = requests.get('https://api.github.com')
# print(response.json())
req=requests.get('https://reqres.in/api/users/2')
print(req.json())
req1=requests.get('https://reqres.in/api/users/2')
print(req1.json())
req2=requests.get('https://reqres.in/api/users?page=2')
print(req2.json())
req3=requests.get('https://reqres.in/api/users/23')
print(req3.json())
req4=requests.get('https://reqres.in/api/unknown')
print(req4.json())
req5=requests.get('https://reqres.in/api/unknown/2')
print(req5.json())
req6=requests.get('https://reqres.in/api/unknown/23')
print(req6.json())
req7=requests.get('https://reqres.in/api/users')
print(req7.json())
req8=requests.get('https://reqres.in/api/users/2')
print(req8.json())
req9=requests.get('https://reqres.in/api/register')
print(req9.json())
req10=requests.get('https://reqres.in/api/register')
print(req10.json())
req11=requests.get('https://reqres.in/api/login')
print(req11.json())
req12=requests.get('https://reqres.in/api/login')
print(req12.json())
req13=requests.get('https://reqres.in/api/login')
print(req13.json())
req14=requests.get('https://reqres.in/api/users?delay=3')
print(req14.json())

